Page content backend
thomas-ayling/amcr-back-end pull request #22
Opened 2023-01-09 09:13 UTC by MihneaDinuGL

The backend for the diagram component.

2023-01-09 16:01 UTC, thomas-ayling requested changes

2023-01-09 16:01 UTC, thomas-ayling commented on src/main/java/com/globallogic/amcr/service/pagecontent/DiagramServiceImpl.java
> +            throw new RuntimeException("Error saving in service implementation", e);
More detail on which method the error was thrown could be useful for debugging

2023-01-09 16:01 UTC, thomas-ayling commented on src/main/java/com/globallogic/amcr/service/pagecontent/DiagramServiceImpl.java
> +            diagramDao.update(diagram, id);
Make sure that the received object is not null

2023-01-11 15:47 UTC, thomas-ayling commented on src/main/java/com/globallogic/amcr/persistence/model/pagecontent/Diagram.java
> +        Assert.notNull(id, "ID is null");
That's outdated now, you can use `Assert.assertNull()` instead

2023-01-11 15:57 UTC, MihneaDinuGL commented on src/main/java/com/globallogic/amcr/mapper/pagecontent/DiagramMapper.java
> +package com.globallogic.amcr.mapper.pagecontent;
Is this something everyone should take into account?

2023-01-12 09:17 UTC, MihneaDinuGL commented on src/main/java/com/globallogic/amcr/persistence/dao/pagecontent/DiagramDao.java
> +        } catch (Exception e){
What kind of exception would be expected to be thrown here? I will change the message so it's more specific as well

2023-01-13 12:04 UTC, MihneaDinuGL commented on src/main/java/com/globallogic/amcr/persistence/dao/pagecontent/DiagramDao.java
> +        } catch (Exception e){
I have tried to be more specific about the error, but I'd be happy to remove it if you consider that better

2023-01-20 11:02 UTC, Kya-Edmeade approved these changes

2023-01-20 11:42 UTC, thomas-ayling approved these changes

2023-01-20 11:43 UTC, merged