Layout
thomas-ayling/amcr-back-end pull request #45
Opened 2023-02-03 12:56 UTC by Kya-Edmeade

2023-02-03 16:57 UTC, sourcesmith requested changes
Remove all the .DS_store files  - we do not need Mac scribblings all over the code base.  This should be in the .gitignore really.

2023-02-03 17:22 UTC, sourcesmith requested changes
Other than the specific comments.  General ones are:
No logging.
Little assertion of arguments.
Possible excessive catching of exceptions.

2023-02-07 15:14 UTC, Kya-Edmeade commented on src/main/java/com/globallogic/amcr/repository/impl/layoutcomponent/LayoutDaoImpl.java
> +        return layoutMapper.getAll();
I'm not sure what you mean by this comment

2023-02-07 15:48 UTC, Kya-Edmeade commented on src/main/resources/application.properties
> +file.upload-dir=/Users/siso/Desktop/Uploads
I believe this is relating to Stanislavs @S1sO0 part

2023-02-11 17:04 UTC, sourcesmith commented on src/main/java/com/globallogic/amcr/controller/layoutcomponent/LayoutController.java
> +        } catch (Exception e) {
You should not really need this handler.

2023-02-15 09:44 UTC, merged